apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb }}

